name: definitions
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
jobs:
  test:
    name: verify
    runs-on: ubuntu-latest
    strategy:
       matrix:
         ruby: [2.4, 2.5, 2.6, 2.7, 3.0, 3.1, 3.2, 'ruby-head']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run tests
        run: make test
      - name: Run validate
        run: make validate
